# Base image
FROM lewg/nginx-pagespeed

# Add files
COPY nginx.conf /etc/nginx/nginx.conf
COPY sites-enabled /etc/nginx/sites-enabled/
COPY credentials /etc/nginx/credentials/
COPY ssl /etc/nginx/ssl/
